### ISSUE TITLE
TODO: break them into seperate routes for example: /livemint etc

### ISSUE THREAD

**Issue by sidmohanty11** [Cryptonaline/Cryptonaline-API#6]
- If you go to `routes/posts.js` you will see a todo there stating the same
- by scraping every website using one endpoint it becomes too slow for the server to fetch results, instead break them down

Tasks:

- [ ] `router.get('/livemint')` etc

**Comment by Sohamkayal4103** [comment]
@sidmohanty11   Can I work on this issue?

**Comment by sidmohanty11** [comment]
@Sohamkayal4103 sure, feel free to tag me if you face any issue

**Comment by rakeshhotker** [comment]
@Sohamkayal4103 have you made any progress on it, i am planning to work on it too, if you are done then i wont start, do let me know

**Comment by Sohamkayal4103** [comment]
I am on it... Will make a PR today
